import { describe, expect, it } from "vitest";

import {
  buildExecutionDocument,
  buildExecutionHistoryDocument,
  buildFinanceMembersDocument,
  buildPRDocument,
  buildPRListDocument,
  buildWorkoutDocument,
  generateExportFile,
  renderCsv,
  renderMarkdown,
  renderText,
  type ExportDocument,
  type ExportLabels,
} from "@/lib/document-export";

const labels: ExportLabels = {
  appName: "TrainingJournal",
  finance: "Finance",
  members: "Members",
  plan: "Plan",
  expires: "Expires",
  lastPaid: "Last paid",
  amount: "Amount",
  credits: "Credits",
  balanceDue: "Balance due",
  referrals: "Referrals",
  workout: "Workout",
  workoutHistory: "WOD History",
  personalRecord: "Personal Record",
  personalRecords: "Personal Records",
  type: "Type",
  status: "Status",
  scale: "Scale",
  scales: "Scales",
  date: "Date",
  source: "Source",
  duration: "Duration",
  sections: "Sections",
  exercises: "Exercises",
  scores: "Scores",
  notes: "Notes",
  modifications: "Modifications",
  supportingDetails: "Supporting details",
  comparison: "Comparison",
  higherIsBetter: "Higher is better",
  lowerIsBetter: "Lower is better",
  prescribed: "Prescribed",
  actual: "Actual",
  baseOnly: "Base only",
  none: "None",
  generatedBy: "Generated by TrainingJournal",
  teamWorkout: "Team workout",
  setsLabel: "sets",
  roundsLabel: "rounds",
  excluded: "excluded",
  basePrescription: "base prescription",
  load: "load",
  yes: "Yes",
  no: "No",
  session: "session",
  score: "Score",
  header: "Header",
  superset: "Superset",
  alternatingSets: "Alternating sets",
  progressiveLoad: "Progressive load",
  progressiveDeload: "Progressive deload",
};

describe("document export adapters", () => {
  it("preserves workout hierarchy and scale variations", () => {
    const document = buildWorkoutDocument({
      id: "w1",
      title: "Engine Builder",
      type: "crossfit",
      status: "published",
      available_scale_levels: [{ slug: "rx", label: "Rx", sort_order: 1, is_active: true }],
      sections: [{
        name: "Main",
        order: 0,
        scoreable: true,
        timer_config: { type: "amrap", duration_seconds: 720 },
        exercises: [{
          name: "Thruster",
          order: 0,
          sets: 3,
          prescription_value: 10,
          prescription_unit: "reps",
          load_value: 40,
          load_mode: "absolute",
          variations: [{
            scale_level: { slug: "rx", label: "Rx", sort_order: 1, is_active: true },
            prescription_value: 8,
          }],
        }],
      }],
    }, labels);

    expect(document.title).toBe("Engine Builder");
    expect(document.sections[0].title).toBe("Main");
    expect(document.sections[0].items[0].value).toContain("3 × 10 reps");
    expect(document.sections[0].items[0].details).toContain("Rx: 3 × 8 reps");
  });

  it("includes the editable section tree when an admin exports a draft workout", () => {
    const document = buildWorkoutDocument({
      id: "draft-1",
      title: "Saturday Chipper",
      type: "crossfit",
      status: "draft",
      available_scale_levels: [],
      sections: [],
      draft_data: {
        sections: [{
          name: "Chipper",
          timer_config: { type: "for_time", duration_seconds: 1_200 },
          scoreable: true,
          exercises: [{
            name: "Box jump",
            sets: 5,
            prescription_value: 12,
            prescription_unit: "reps",
            variations: [{ scale_level_slug: "scaled", prescription_value: 8 }],
          }],
        }],
      },
    }, labels);

    expect(document.metadata).toContainEqual({ label: "Sections", value: "1" });
    expect(document.sections[0].title).toBe("Chipper");
    expect(document.sections[0].items[0].value).toBe("5 × 12 reps");
    expect(document.sections[0].items[0].details).toContain("scaled: 5 × 8 reps");
  });

  it("exports structured groups, headers, notes, per-set reps, and deloads", () => {
    const document = buildWorkoutDocument({
      id: "structured-1",
      title: "Strength complex",
      type: "strength",
      status: "published",
      available_scale_levels: [],
      sections: [{
        name: "Main",
        note: "Keep the bar close",
        order: 0,
        scoreable: false,
        exercises: [{
          item_type: "header",
          name: "Barbell complex",
          note: "No rest between movements",
          order: 0,
          variations: [],
        }, {
          item_type: "exercise",
          name: "Back squat",
          order: 1,
          sets: 3,
          prescription_value: 10,
          prescription_unit: "reps",
          set_prescriptions: [
            { set_index: 1, prescription_value: 10, prescription_unit: "reps", note: "Controlled" },
            { set_index: 2, prescription_value: 8, prescription_unit: "reps" },
            { set_index: 3, prescription_value: 6, prescription_unit: "reps" },
          ],
          load_progression: {
            mode: "linear",
            direction: "decrease",
            start_value: 80,
            start_mode: "pct_1rm",
            step_value: 5,
            per_set_values: [],
          },
          superset_group_id: "group-1",
          note: "Brace before every rep",
          variations: [],
        }],
      }],
    }, labels);

    const output = renderText(document);
    expect(output).toContain("Notes: Keep the bar close");
    expect(output).toContain("Header: Barbell complex");
    expect(output).toContain("No rest between movements");
    expect(output).toContain("Superset");
    expect(output).toContain("sets 2: 8 reps");
    expect(output).toContain("Progressive deload: 80 %1RM (−5 %1RM/sets)");
    expect(output).toContain("Brace before every rep");
  });

  it("includes execution scores, notes, and actual-vs-prescribed modifications", () => {
    const document = buildExecutionDocument({
      id: "e1",
      user_id: "u1",
      master_workout_id: "w1",
      workout_title: "Fran",
      workout_type: "crossfit",
      scale_level_slug: "scaled",
      source: "self_selected",
      source_reference_id: null,
      status: "completed",
      started_at_utc: "2026-07-18T08:00:00Z",
      started_at_tz: "Europe/Athens",
      completed_at_utc: "2026-07-18T08:07:30Z",
      completed_at_tz: "Europe/Athens",
      current_segment_index: 1,
      segment_started_at_utc: null,
      paused_elapsed_ms: 0,
      resume_countdown_ends_at_utc: null,
      total_elapsed_ms: 450_000,
      section_elapsed_ms: {},
      segment_cycle_counts: {},
      checked_exercise_ids: [],
      section_scores: [{ section_id: "s1", section_name: "For time", value: 450, unit: "seconds" }],
      exercise_notes: [{ id: "n1", exercise_id: "x1", selected_text: "Pull-ups", note_text: "Strict" }],
      exercise_modifications: [{
        field: "reps",
        section_id: "s1",
        exercise_name: "Thruster",
        canonical_value: 21,
        actual_value: 18,
      }],
      lock_version: 1,
      inserted_at: "2026-07-18T08:00:00Z",
    }, labels, "en");

    expect(document.sections.map((section) => section.title)).toEqual(["Scores", "Modifications", "Notes"]);
    expect(renderText(document)).toContain("Prescribed: 21 → Actual: 18");
  });

  it("produces readable markdown and spreadsheet-safe CSV for a PR", () => {
    const document = buildPRDocument({
      id: "p1",
      user_id: "u1",
      name: "Back squat",
      current_score: 140,
      unit: "kg",
      higher_is_better: true,
      beaten_on: "2026-07-18",
      supporting_metrics: { reps: 3, sets: 2 },
      notes: "Smooth, no belt",
      inserted_at: "2026-07-18T08:00:00Z",
      updated_at: "2026-07-18T08:00:00Z",
    }, labels, "en");

    expect(renderMarkdown(document)).toContain("# 🏆 Back squat");
    expect(renderMarkdown(document)).toContain("**Score:** 140 kg");
    expect(renderCsv(document)).toContain('"Supporting details","Sets","2"');
    expect(renderCsv(document)).toContain('"Notes","","Smooth, no belt"');
  });

  it("exports the complete Pantheon collection in one document", () => {
    const first = {
      id: "p1", user_id: "u1", name: "Back squat", current_score: 140, unit: "kg" as const,
      higher_is_better: true, beaten_on: "2026-07-18", supporting_metrics: {}, notes: null,
      inserted_at: "2026-07-18T08:00:00Z", updated_at: "2026-07-18T08:00:00Z",
    };
    const document = buildPRListDocument([
      first,
      { ...first, id: "p2", name: "Deadlift", current_score: 180 },
    ], labels, "en");

    expect(document.title).toBe("Personal Records");
    expect(renderText(document)).toContain("Back squat");
    expect(renderText(document)).toContain("Deadlift");
  });

  it("exports the complete workout history in one document", () => {
    const execution = {
      id: "e1", user_id: "u1", master_workout_id: null, workout_title: "Fran", workout_type: "crossfit",
      scale_level_slug: null, source: "self_selected", source_reference_id: null, status: "completed" as const,
      started_at_utc: "2026-07-18T08:00:00Z", started_at_tz: "Europe/Athens",
      completed_at_utc: "2026-07-18T08:07:30Z", completed_at_tz: "Europe/Athens",
      current_segment_index: 1, segment_started_at_utc: null, paused_elapsed_ms: 0,
      resume_countdown_ends_at_utc: null, total_elapsed_ms: 450_000, section_elapsed_ms: {},
      segment_cycle_counts: {}, checked_exercise_ids: [], section_scores: [], exercise_notes: [],
      exercise_modifications: [], lock_version: 1, inserted_at: "2026-07-18T08:00:00Z",
    };
    const document = buildExecutionHistoryDocument([
      execution,
      { ...execution, id: "e2", workout_title: "Helen" },
    ], labels, "en");

    expect(document.title).toBe("WOD History");
    expect(renderText(document)).toContain("Fran");
    expect(renderText(document)).toContain("Helen");
  });

  it("generates real PDF and ODT containers", async () => {
    const document = buildPRDocument({
      id: "p2",
      user_id: "u1",
      name: "Deadlift",
      current_score: 180,
      unit: "kg",
      higher_is_better: true,
      beaten_on: "2026-07-18",
      supporting_metrics: {},
      notes: null,
      inserted_at: "2026-07-18T08:00:00Z",
      updated_at: "2026-07-18T08:00:00Z",
    }, labels, "en");

    const pdf = await generateExportFile(document, "pdf");
    const odt = await generateExportFile(document, "odt");
    const pdfBytes = new Uint8Array(await pdf.arrayBuffer());
    const { default: JSZip } = await import("jszip");
    const odtArchive = await JSZip.loadAsync(await odt.arrayBuffer());

    expect(new TextDecoder().decode(pdfBytes.slice(0, 5))).toBe("%PDF-");
    expect(await odtArchive.file("mimetype")?.async("string")).toBe("application/vnd.oasis.opendocument.text");
    const odtContent = await odtArchive.file("content.xml")?.async("string");
    expect(odtContent).toContain("Deadlift");
    expect(odtContent).toContain("🏆");
    expect(odtContent).toContain('fo:color="#7C3AED"');
  });

  it("keeps wrapped metadata and long paragraph details in the PDF", async () => {
    const longMetadata = "A complete membership note that must survive PDF wrapping without losing its final words.";
    const longDetail = "Coach instruction: keep each repetition controlled, record the adjustment, and retain this complete paragraph on the following line when required.";
    const document: ExportDocument = {
      icon: "📄",
      category: "Export",
      title: "Complete document",
      metadata: [{ label: "Summary", value: longMetadata }],
      sections: [{
        icon: "📝",
        title: "Long-form notes",
        items: [{ label: "Instruction", value: longDetail }],
      }],
      footer: "TrainingJournal",
    };

    const file = await generateExportFile(document, "pdf");
    const pdf = new TextDecoder().decode(await file.arrayBuffer());

    expect(pdf).toContain("final words.");
    expect(pdf).toContain("following line when required.");
  });

  it("continues overflowing content onto later PDF pages", async () => {
    const document: ExportDocument = {
      icon: "📄",
      category: "Export",
      title: "Paginated document",
      metadata: [],
      sections: [{
        icon: "📝",
        title: "Entries",
        items: Array.from({ length: 90 }, (_, index) => ({
          label: `Entry ${index + 1}`,
          value: `The complete content for entry ${index + 1} is retained across page boundaries.`,
        })),
      }],
      footer: "TrainingJournal",
    };

    const file = await generateExportFile(document, "pdf");
    const pdf = new TextDecoder().decode(await file.arrayBuffer());

    expect(pdf.match(/\/Type \/Page\b/g)?.length).toBeGreaterThan(1);
    expect(pdf).toContain("complete content for entry 90");
  });

  it("preserves every visible finance member field for export", () => {
    const document = buildFinanceMembersDocument([{
      id: "member-1",
      nickname: "Niko",
      identity_role: "member",
      membership: { status: "active", notes: "Needs a receipt with the full billing address." },
      active_package_subscription: { package_code_snapshot: "UNLIMITED", ends_on: "2026-08-31" },
      last_payment_on: "2026-07-01",
      last_payment_amount_cents: 8500,
      credit_balance_cents: 1000,
      outstanding_balance_cents: 1200,
      referrals_made_user_ids: ["u-2", "u-3"],
    }], labels, "en");

    const exported = renderText(document);
    expect(document.category).toBe("Finance");
    expect(exported).toContain("Niko");
    expect(exported).toContain("Needs a receipt with the full billing address.");
    expect(exported).toContain("UNLIMITED");
    expect(exported).toContain("€85.00");
    expect(exported).toContain("2");
  });
});
