[
  {"lib/milos_training/application/create_pr.ex", "The guard clause can never succeed."},
  {"lib/milos_training/application/get_landing_page.ex",
   "The pattern can never match the type false."},
  {"lib/milos_training/application/get_schedule_calendar.ex",
   "The pattern can never match the type {:error, :incompatible_calendars | :invalid_date | :invalid_format}."},
  {"lib/milos_training/application/ports/token_issuer.ex",
   "Unknown type: MilosTraining.Identity.Account.t/0."},
  {"lib/milos_training/application/ports/token_verifier.ex",
   "Unknown type: MilosTraining.Identity.Account.t/0."},
  {"lib/milos_training/application/submit_review.ex",
   "The pattern variable __type@1 can never match the type, because it is covered by previous clauses."},
  {"lib/milos_training/coaching/domain/athlete_drill_down.ex",
   "The guard clause can never succeed."},
  {"lib/milos_training/finance/domain/member_drill_down.ex",
   "The guard clause can never succeed."},
  {"lib/milos_training/gamification/domain/challenge_progress.ex",
   "The pattern can never match the type true."},
  {"lib/milos_training/identity/ports/user_store.ex",
   "Unknown type: MilosTraining.Identity.Account.t/0."},
  {"lib/milos_training/infrastructure/feedback/ecto_feedback_store.ex",
   "Function Decimal.to_float/1 does not exist."},
  {"lib/milos_training/infrastructure/finance/ecto_finance_store.ex",
   "Function Decimal.to_integer/1 does not exist."},
  {"lib/milos_training/infrastructure/notifications/web_push_dispatcher.ex",
   "The pattern variable _reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/milos_training/infrastructure/pantheon/ecto_pr_store.ex",
   "Function Decimal.to_float/1 does not exist."},
  {"lib/milos_training/infrastructure/readiness/live.ex",
   "Function status/0 has no local return."},
  {"lib/milos_training/infrastructure/readiness/live.ex",
   "Function object_storage_status/0 has no local return."},
  {"lib/milos_training/infrastructure/readiness/live.ex",
   "Function ready?/1 will never be called."},
  {"lib/milos_training/infrastructure/readiness/live.ex",
   "Function failed_checks/1 will never be called."},
  {"lib/milos_training/infrastructure/storage/bucket_reconciler.ex",
   "Function handle_info/2 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function ensure_buckets/0 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "The function call ensure_bucket will not succeed."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function health_status/0 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "The function call request will not succeed."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function presigned_upload_post/2 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function validate_uploaded_document/2 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function create_upload/3 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "The function call request_avatar_probe will not succeed."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function request_avatar_probe/4 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function request_public_avatar_probe/1 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function validate_avatar_size/1 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function validate_document_content_type/2 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function document_byte_size/1 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function validate_document_size/2 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function avatar_validation_reason/1 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function ensure_bucket/2 has no local return."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function create_bucket/2 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function ensure_avatar_read_policy/2 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function normalized_header_value/2 will never be called."},
  {"lib/milos_training/infrastructure/storage/minio_storage.ex",
   "Function header_value/2 will never be called."},
  {"lib/milos_training/messaging/ports/message_store.ex",
   "Unknown type: MilosTraining.Messaging.Message.t/0."},
  {"lib/milos_training/messaging/ports/thread_store.ex",
   "Unknown type: MilosTraining.Messaging.Thread.t/0."},
  {"lib/milos_training/messaging/ports/thread_store.ex",
   "Unknown type: MilosTraining.Messaging.Participant.t/0."},
  {"lib/milos_training/organizations/ports/organization_store.ex",
   "Unknown type: MilosTraining.Organizations.Organization.t/0."},
  {"lib/milos_training/organizations/ports/organization_store.ex",
   "Unknown type: MilosTraining.Organizations.OrganizationMembership.t/0."},
  {"lib/milos_training/organizations/ports/organization_store.ex",
   "Unknown type: MilosTraining.Organizations.RegistrationInvitation.t/0."},
  {"lib/milos_training/organizations/ports/organization_store.ex",
   "Unknown type: MilosTraining.Organizations.OrganizationSetting.t/0."},
  {"lib/milos_training_web/controllers/admin_wellbeing_controller.ex",
   "The guard clause can never succeed."},
  {"lib/milos_training_web/controllers/me_controller.ex",
   "The pattern can never match the type %Plug.Conn.Unfetched{:aspect => atom(), binary() => _}."},
  {"lib/milos_training_web/controllers/review_controller.ex",
   "The guard clause can never succeed."},
  {"lib/milos_training_web/controllers/wellbeing_controller.ex",
   "The guard clause can never succeed."}
]
