ARG API_DEV_BASE_IMAGE=elixir:1.18.4-otp-27-alpine
FROM ${API_DEV_BASE_IMAGE}

RUN apk add --no-cache build-base git inotify-tools

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

CMD ["mix", "phx.server"]
